name: Ruff Formatting
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
        src: './src/python'
        args: 'format --target-version py310'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
        commit_message: 'Style fixes by ruff'
