[package]
name = "oxli"
version = "0.2.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "oxli"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version="0.22.2", features = ["extension-module", "anyhow"] }
sourmash = "0.15.1"
anyhow = "1.0.87"
log = "0.4.22"
env_logger = "0.11.5"

# For JSON serialization/deserialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# For Gzip compression/decompression
flate2 = "1.0"